/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 src/assets/models/coke.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei';

import Coke from '../models/coke.glb';

export function CokeModel(props) {
  const { nodes, materials } = useGLTF(Coke)
  
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.imagetostl_mesh.geometry}
        material={materials.mat0}
      />
    </group>
  )
}

useGLTF.preload(Coke)
