/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 src/assets/models/house.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import House from '../models/house.glb';

export function HouseModel(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(House)

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh 
        geometry={nodes.Cube.geometry} 
        material={materials.cottage_texture}
        rotation={[-Math.PI / 2, 0, -3.07]} 
        scale={[3, 3, 3]}
      />
    </group>
  )
}

useGLTF.preload(House)
