/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 src/assets/models/xbox.glb --transform --types
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

import Xbox from '../models/xbox-transformed.glb'

type GLTFResult = GLTF & {
  nodes: {
    node_id30: THREE.Mesh
  }
  materials: {
    ['405']: THREE.MeshStandardMaterial
  }
}

export function XboxModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(Xbox) as unknown as GLTFResult
  return (
    <group {...props} dispose={null} scale={1} position={[0,-2,0]}>
      <mesh
        geometry={nodes.node_id30.geometry}
        material={materials['405']}
      />
    </group>
  )
}

useGLTF.preload(Xbox)
